### ISSUE TITLE
Logo Distortion

### ISSUE THREAD

**Issue by loua0013** [loua0013/web-design-2-independent-project#1]
Hey @mackenzierose! I can't believe i'm having this newbie issue, but do you know why my logo is acting up like this? Its distorting! I tried giving it a fixed percentage height and width but it's still being mischeivious!

Hope you're doing well! Thanks for the help!

**Comment by MacKenzieRose** [comment]
No self-berating for having issues. I run into this kind of thing all the time.

The short solution to stop your logo from distorting is to specify the height value in your logo class as `height: 100%` which will force the ratio to remain constant for the image.

In the long run, you might want to consider throwing the header content (with the navigation elements too) into a css grid (as you learned a little bit about earlier in the semester). 

I hope that helps; keep tagging me if it doesn't 😸

**Comment by loua0013** [comment]
Thank you so much! It works! That is a good idea! I'm just throwing in the content but I'm still working on structure!

Thank you!!!!!
