### ISSUE TITLE
CSS not workingon some elements of second page of html  

### ISSUE THREAD

**Issue by loua0013** [loua0013/web-design-2-independent-project#2]
Hi @MackenzieRose and @HellaChella!

I am working on the second page of my website and I'm wondering why my nav bar, h1 and paragraph under the class description are not being affected by my CSS (they are on the homepage). The text is much bigger than in my homepage!

Thank you!

**Comment by MacKenzieRose** [comment]
Hi!

I took a look, and the pages seem to have the same styling; were you able to fix this issue? If not, make sure all of your code is pushed, and if you can, could you grab some screenshots to show me where the problem is?

😄
